import { Octokit } from '@octokit/rest';

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

/**
 * Fetches the changed files and their patches for a PR.
 * Returns a formatted diff string capped at ~100KB to control Claude token usage.
 */
export async function getPRFiles(repo, prNumber) {
  const [owner, repoName] = repo.split('/');

  const { data: files } = await octokit.pulls.listFiles({
    owner,
    repo: repoName,
    pull_number: prNumber,
    per_page: 50,
  });

  const diff = files
    .filter(f => f.patch) // binary files and files too large have no patch
    .map(f => `--- a/${f.filename}\n+++ b/${f.filename}\n${f.patch}`)
    .join('\n\n');

  if (diff.length > 100_000) {
    return diff.slice(0, 100_000) + '\n\n... (diff truncated — too large to review fully)';
  }
  return diff;
}

/**
 * Posts the review as a PR comment.
 * Formats the review object into readable GitHub markdown.
 */
export async function postReview(repo, prNumber, review, commitId) {
  const [owner, repoName] = repo.split('/');

  const body = formatReviewBody(review);

  await octokit.pulls.createReview({
    owner,
    repo: repoName,
    pull_number: prNumber,
    commit_id: commitId,
    body,
    event: 'COMMENT',
  });
}

function formatReviewBody(review) {
  let body = `## 🤖 Code Review\n\n${review.summary}`;

  if (review.issues && review.issues.length > 0) {
    body += '\n\n### Issues\n\n';
    for (const issue of review.issues) {
      const severity = issue.severity === 'high' ? '🔴' : issue.severity === 'medium' ? '🟡' : '🔵';
      body += `${severity} **\`${issue.file}\`** — ${issue.comment}\n\n`;
    }
  }

  if (review.positives && review.positives.length > 0) {
    body += '\n\n### Looks Good\n\n';
    for (const item of review.positives) {
      body += `✅ ${item}\n`;
    }
  }

  body += '\n\n---\n*Generated by CodeReviewBot using Claude*';
  return body;
}
