import { Octokit } from '@octokit/rest';

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

/**
 * Fetches changed files for a PR and returns a formatted diff string.
 */
export async function getPRFiles(repo, prNumber) {
  const [owner, repoName] = repo.split('/');

  // per_page: 50 — GitHub's default is 30, cap is 100. 50 keeps payloads
  // manageable while still covering most PRs in a single request.
  const { data: files } = await octokit.pulls.listFiles({
    owner,
    repo: repoName,
    pull_number: prNumber,
    per_page: 50,
  });

  return buildDiff(files);
}

/**
 * Fetches changed files for a specific commit and returns a formatted diff string.
 */
export async function getCommitFiles(repo, sha) {
  const [owner, repoName] = repo.split('/');

  const { data: commit } = await octokit.repos.getCommit({
    owner,
    repo: repoName,
    ref: sha,
  });

  return buildDiff(commit.files || []);
}

function buildDiff(files) {
  const diff = files
    // Skip deleted files (no patch to review) and files with no diff data.
    .filter(f => f.patch && f.status !== 'removed')
    // Format as a standard unified diff so the AI model can parse it easily.
    .map(f => `--- a/${f.filename}\n+++ b/${f.filename}\n${f.patch}`)
    .join('\n\n');

  // Hard cap at 100KB to stay within model context limits and avoid runaway costs.
  if (diff.length > 100_000) {
    return diff.slice(0, 100_000) + '\n\n... (diff truncated — too large to review fully)';
  }
  return diff;
}

/**
 * Returns true if the bot already reviewed this specific commit on a PR.
 * Keyed by commit SHA so each new push to a PR gets its own review.
 */
export async function hasAlreadyReviewed(repo, prNumber, commitSha) {
  const [owner, repoName] = repo.split('/');
  const { data: reviews } = await octokit.pulls.listReviews({
    owner,
    repo: repoName,
    pull_number: prNumber,
  });
  // Match both the bot marker (so we don't flag human reviews) and the exact
  // commit SHA so a new push to the same PR always gets its own fresh review.
  return reviews.some(r =>
    r.body &&
    r.body.includes('🤖 Code Review') &&
    r.commit_id === commitSha
  );
}

/**
 * Returns true if the bot already posted a review comment on this commit.
 */
export async function hasCommitReview(repo, sha) {
  const [owner, repoName] = repo.split('/');
  const { data: comments } = await octokit.repos.listCommentsForCommit({
    owner,
    repo: repoName,
    commit_sha: sha,
  });
  return comments.some(c => c.body.includes('🤖 Code Review'));
}

/**
 * Posts a PR review comment.
 */
export async function postReview(repo, prNumber, review, commitId) {
  const [owner, repoName] = repo.split('/');

  await octokit.pulls.createReview({
    owner,
    repo: repoName,
    pull_number: prNumber,
    commit_id: commitId,
    body: formatReviewBody(review),
    event: 'COMMENT',
  });
}

/**
 * Posts a review comment directly on a commit.
 */
export async function postCommitComment(repo, sha, review) {
  const [owner, repoName] = repo.split('/');

  await octokit.repos.createCommitComment({
    owner,
    repo: repoName,
    commit_sha: sha,
    body: formatReviewBody(review),
  });
}

function formatReviewBody(review) {
  let body = `## 🤖 Code Review\n\n${review.summary}`;

  if (review.issues && review.issues.length > 0) {
    body += '\n\n### Issues\n\n';
    for (const issue of review.issues) {
      const severity = issue.severity === 'high' ? '🔴' : issue.severity === 'medium' ? '🟡' : '🔵';
      body += `${severity} **\`${issue.file}\`** — ${issue.comment}\n\n`;
    }
  }

  if (review.positives && review.positives.length > 0) {
    body += '\n\n### Looks Good\n\n';
    for (const item of review.positives) {
      body += `✅ ${item}\n`;
    }
  }

  body += '\n\n---\n*Generated by CodeReviewBot using Gemini*';
  return body;
}
